import { DataTypes } from 'sequelize';
import { baseFields, baseOptions } from './baseModel.js';

export default function(sequelize) {
  const Settings = sequelize.define('Settings', {
    ...baseFields,
    subscription_system_enabled: { type: DataTypes.BOOLEAN, allowNull: true },
    default_recording_access_days: { type: DataTypes.DECIMAL, allowNull: true },
    recording_lifetime_access: { type: DataTypes.BOOLEAN, allowNull: true },
    default_course_access_days: { type: DataTypes.DECIMAL, allowNull: true },
    course_lifetime_access: { type: DataTypes.BOOLEAN, allowNull: true },
    default_file_access_days: { type: DataTypes.DECIMAL, allowNull: true },
    file_lifetime_access: { type: DataTypes.BOOLEAN, allowNull: true },
    contact_email: { type: DataTypes.STRING, allowNull: true },
    contact_phone: { type: DataTypes.STRING, allowNull: true },
    site_description: { type: DataTypes.TEXT, allowNull: true },
    logo_url: { type: DataTypes.STRING, allowNull: true },
    site_name: { type: DataTypes.STRING, allowNull: true },
    maintenance_mode: { type: DataTypes.BOOLEAN, allowNull: true },
    student_invitation_expiry_days: { type: DataTypes.DECIMAL, allowNull: true },
    parent_consent_required: { type: DataTypes.BOOLEAN, allowNull: true },
    nav_order: { type: DataTypes.JSONB, allowNull: true },
    nav_files_text: { type: DataTypes.STRING, allowNull: true },
    nav_files_icon: { type: DataTypes.STRING, allowNull: true },
    nav_files_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_files_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: true },
    nav_games_text: { type: DataTypes.STRING, allowNull: true },
    nav_games_icon: { type: DataTypes.STRING, allowNull: true },
    nav_games_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'public' },
    nav_games_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    nav_workshops_text: { type: DataTypes.STRING, allowNull: true },
    nav_workshops_icon: { type: DataTypes.STRING, allowNull: true },
    nav_workshops_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_workshops_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    nav_courses_text: { type: DataTypes.STRING, allowNull: true },
    nav_courses_icon: { type: DataTypes.STRING, allowNull: true },
    nav_courses_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_courses_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    nav_classrooms_text: { type: DataTypes.STRING, allowNull: true },
    nav_classrooms_icon: { type: DataTypes.STRING, allowNull: true },
    nav_classrooms_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_classrooms_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    nav_account_text: { type: DataTypes.STRING, allowNull: true },
    nav_account_icon: { type: DataTypes.STRING, allowNull: true },
    nav_account_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_account_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: true },
    nav_content_creators_text: { type: DataTypes.STRING, allowNull: true },
    nav_content_creators_icon: { type: DataTypes.STRING, allowNull: true },
    nav_content_creators_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'admins_and_creators' },
    nav_content_creators_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    nav_tools_text: { type: DataTypes.STRING, allowNull: true },
    nav_tools_icon: { type: DataTypes.STRING, allowNull: true },
    nav_tools_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'admin_only' },
    nav_tools_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: true },
    nav_curriculum_text: { type: DataTypes.STRING, allowNull: true },
    nav_curriculum_icon: { type: DataTypes.STRING, allowNull: true },
    nav_curriculum_visibility: { type: DataTypes.STRING, allowNull: true, defaultValue: 'logged_in_users' },
    nav_curriculum_enabled: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: false },
    allow_content_creator_workshops: { type: DataTypes.BOOLEAN, allowNull: true },
    allow_content_creator_courses: { type: DataTypes.BOOLEAN, allowNull: true },
    allow_content_creator_files: { type: DataTypes.BOOLEAN, allowNull: true },
    allow_content_creator_tools: { type: DataTypes.BOOLEAN, allowNull: true },
    allow_content_creator_games: { type: DataTypes.BOOLEAN, allowNull: true },
    copyright_footer_text: { type: DataTypes.TEXT, allowNull: true },
    footer_settings: { type: DataTypes.JSONB, allowNull: true },
    available_dashboard_widgets: { type: DataTypes.JSONB, allowNull: true, comment: 'Available widgets for user dashboards' },
    available_specializations: { type: DataTypes.JSONB, allowNull: true, comment: 'Available specializations for teacher onboarding' },
    available_grade_levels: { type: DataTypes.JSONB, allowNull: true, comment: 'Available grade levels for classroom creation' },
  }, {
    ...baseOptions,
    tableName: 'settings',
  });

  return Settings;
}